name = "kuuzuki-web"
main = "./dist/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_URL = "https://kuuzuki.com"

# Development environment
[env.development]
name = "kuuzuki-web-dev"

[env.development.vars]
SITE_URL = "https://dev.kuuzuki.com"

# Production environment  
[env.production]
name = "kuuzuki-web-prod"

[env.production.vars]
SITE_URL = "https://kuuzuki.com"