# coding: utf-8

"""
    kuuzuki

    kuuzuki API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kuuzuki_ai.models.send_message_request import SendMessageRequest

class TestSendMessageRequest(unittest.TestCase):
    """SendMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendMessageRequest:
        """Test SendMessageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendMessageRequest`
        """
        model = SendMessageRequest()
        if include_optional:
            return SendMessageRequest(
                text = '',
                files = [
                    kuuzuki_ai.models.send_message_request_files_inner.SendMessageRequest_files_inner(
                        path = '',
                        content = '', )
                    ]
            )
        else:
            return SendMessageRequest(
        )
        """

    def testSendMessageRequest(self):
        """Test SendMessageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
