# coding: utf-8

"""
    kuuzuki

    kuuzuki API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kuuzuki_ai.models.app_time import AppTime

class TestAppTime(unittest.TestCase):
    """AppTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppTime:
        """Test AppTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppTime`
        """
        model = AppTime()
        if include_optional:
            return AppTime(
                initialized = 1.337
            )
        else:
            return AppTime(
        )
        """

    def testAppTime(self):
        """Test AppTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
