# coding: utf-8

"""
    kuuzuki

    kuuzuki API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kuuzuki_ai.models.create_session_request import CreateSessionRequest

class TestCreateSessionRequest(unittest.TestCase):
    """CreateSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSessionRequest:
        """Test CreateSessionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSessionRequest`
        """
        model = CreateSessionRequest()
        if include_optional:
            return CreateSessionRequest(
                provider_id = '',
                model = '',
                system = ''
            )
        else:
            return CreateSessionRequest(
        )
        """

    def testCreateSessionRequest(self):
        """Test CreateSessionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
