# coding: utf-8

"""
    kuuzuki

    kuuzuki API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kuuzuki_ai.models.send_message_request_files_inner import SendMessageRequestFilesInner

class TestSendMessageRequestFilesInner(unittest.TestCase):
    """SendMessageRequestFilesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendMessageRequestFilesInner:
        """Test SendMessageRequestFilesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendMessageRequestFilesInner`
        """
        model = SendMessageRequestFilesInner()
        if include_optional:
            return SendMessageRequestFilesInner(
                path = '',
                content = ''
            )
        else:
            return SendMessageRequestFilesInner(
        )
        """

    def testSendMessageRequestFilesInner(self):
        """Test SendMessageRequestFilesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
