# coding: utf-8

"""
    kuuzuki

    kuuzuki API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kuuzuki_ai.models.provider import Provider

class TestProvider(unittest.TestCase):
    """Provider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Provider:
        """Test Provider
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Provider`
        """
        model = Provider()
        if include_optional:
            return Provider(
                api = '',
                name = '',
                env = [
                    ''
                    ],
                id = '',
                npm = '',
                models = {
                    'key' : kuuzuki_ai.models.model.Model(
                        id = '',
                        name = '',
                        release_date = '',
                        attachment = True,
                        reasoning = True,
                        temperature = True,
                        tool_call = True,
                        cost = kuuzuki_ai.models.model_cost.Model_cost(
                            input = 1.337,
                            output = 1.337,
                            cache_read = 1.337,
                            cache_write = 1.337, ),
                        limit = kuuzuki_ai.models.model_limit.Model_limit(
                            context = 1.337,
                            output = 1.337, ),
                        options = { }, )
                    }
            )
        else:
            return Provider(
        )
        """

    def testProvider(self):
        """Test Provider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
