/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppPath } from './AppPath';
import {
    AppPathFromJSON,
    AppPathFromJSONTyped,
    AppPathToJSON,
    AppPathToJSONTyped,
} from './AppPath';
import type { AppTime } from './AppTime';
import {
    AppTimeFromJSON,
    AppTimeFromJSONTyped,
    AppTimeToJSON,
    AppTimeToJSONTyped,
} from './AppTime';

/**
 *
 * @export
 * @interface App
 */
export interface App {
    /**
     *
     * @type {string}
     * @memberof App
     */
    hostname?: string;
    /**
     *
     * @type {boolean}
     * @memberof App
     */
    git?: boolean;
    /**
     *
     * @type {AppPath}
     * @memberof App
     */
    path?: AppPath;
    /**
     *
     * @type {AppTime}
     * @memberof App
     */
    time?: AppTime;
}

/**
 * Check if a given object implements the App interface.
 */
export function instanceOfApp(value: object): value is App {
    return true;
}

export function AppFromJSON(json: any): App {
    return AppFromJSONTyped(json, false);
}

export function AppFromJSONTyped(json: any, ignoreDiscriminator: boolean): App {
    if (json == null) {
        return json;
    }
    return {

        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'git': json['git'] == null ? undefined : json['git'],
        'path': json['path'] == null ? undefined : AppPathFromJSON(json['path']),
        'time': json['time'] == null ? undefined : AppTimeFromJSON(json['time']),
    };
}

export function AppToJSON(json: any): App {
    return AppToJSONTyped(json, false);
}

export function AppToJSONTyped(value?: App | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'hostname': value['hostname'],
        'git': value['git'],
        'path': AppPathToJSON(value['path']),
        'time': AppTimeToJSON(value['time']),
    };
}
