/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Provider } from './Provider';
import {
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
    ProviderToJSONTyped,
} from './Provider';

/**
 *
 * @export
 * @interface AppProvidersResponse
 */
export interface AppProvidersResponse {
    /**
     *
     * @type {Array<Provider>}
     * @memberof AppProvidersResponse
     */
    providers?: Array<Provider>;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof AppProvidersResponse
     */
    _default?: { [key: string]: string; };
}

/**
 * Check if a given object implements the AppProvidersResponse interface.
 */
export function instanceOfAppProvidersResponse(value: object): value is AppProvidersResponse {
    return true;
}

export function AppProvidersResponseFromJSON(json: any): AppProvidersResponse {
    return AppProvidersResponseFromJSONTyped(json, false);
}

export function AppProvidersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppProvidersResponse {
    if (json == null) {
        return json;
    }
    return {

        'providers': json['providers'] == null ? undefined : ((json['providers'] as Array<any>).map(ProviderFromJSON)),
        '_default': json['default'] == null ? undefined : json['default'],
    };
}

export function AppProvidersResponseToJSON(json: any): AppProvidersResponse {
    return AppProvidersResponseToJSONTyped(json, false);
}

export function AppProvidersResponseToJSONTyped(value?: AppProvidersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'providers': value['providers'] == null ? undefined : ((value['providers'] as Array<any>).map(ProviderToJSON)),
        'default': value['_default'],
    };
}
