/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AppTime
 */
export interface AppTime {
    /**
     *
     * @type {number}
     * @memberof AppTime
     */
    initialized?: number;
}

/**
 * Check if a given object implements the AppTime interface.
 */
export function instanceOfAppTime(value: object): value is AppTime {
    return true;
}

export function AppTimeFromJSON(json: any): AppTime {
    return AppTimeFromJSONTyped(json, false);
}

export function AppTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppTime {
    if (json == null) {
        return json;
    }
    return {

        'initialized': json['initialized'] == null ? undefined : json['initialized'],
    };
}

export function AppTimeToJSON(json: any): AppTime {
    return AppTimeToJSONTyped(json, false);
}

export function AppTimeToJSONTyped(value?: AppTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'initialized': value['initialized'],
    };
}
