/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModelCost
 */
export interface ModelCost {
    /**
     *
     * @type {number}
     * @memberof ModelCost
     */
    input?: number;
    /**
     *
     * @type {number}
     * @memberof ModelCost
     */
    output?: number;
    /**
     *
     * @type {number}
     * @memberof ModelCost
     */
    cacheRead?: number;
    /**
     *
     * @type {number}
     * @memberof ModelCost
     */
    cacheWrite?: number;
}

/**
 * Check if a given object implements the ModelCost interface.
 */
export function instanceOfModelCost(value: object): value is ModelCost {
    return true;
}

export function ModelCostFromJSON(json: any): ModelCost {
    return ModelCostFromJSONTyped(json, false);
}

export function ModelCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCost {
    if (json == null) {
        return json;
    }
    return {

        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'cacheRead': json['cache_read'] == null ? undefined : json['cache_read'],
        'cacheWrite': json['cache_write'] == null ? undefined : json['cache_write'],
    };
}

export function ModelCostToJSON(json: any): ModelCost {
    return ModelCostToJSONTyped(json, false);
}

export function ModelCostToJSONTyped(value?: ModelCost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'input': value['input'],
        'output': value['output'],
        'cache_read': value['cacheRead'],
        'cache_write': value['cacheWrite'],
    };
}
