/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModelLimit
 */
export interface ModelLimit {
    /**
     *
     * @type {number}
     * @memberof ModelLimit
     */
    context?: number;
    /**
     *
     * @type {number}
     * @memberof ModelLimit
     */
    output?: number;
}

/**
 * Check if a given object implements the ModelLimit interface.
 */
export function instanceOfModelLimit(value: object): value is ModelLimit {
    return true;
}

export function ModelLimitFromJSON(json: any): ModelLimit {
    return ModelLimitFromJSONTyped(json, false);
}

export function ModelLimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelLimit {
    if (json == null) {
        return json;
    }
    return {

        'context': json['context'] == null ? undefined : json['context'],
        'output': json['output'] == null ? undefined : json['output'],
    };
}

export function ModelLimitToJSON(json: any): ModelLimit {
    return ModelLimitToJSONTyped(json, false);
}

export function ModelLimitToJSONTyped(value?: ModelLimit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'context': value['context'],
        'output': value['output'],
    };
}
