/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Mode
 */
export interface Mode {
    /**
     *
     * @type {string}
     * @memberof Mode
     */
    model?: string;
    /**
     *
     * @type {string}
     * @memberof Mode
     */
    prompt?: string;
    /**
     *
     * @type {{ [key: string]: boolean; }}
     * @memberof Mode
     */
    tools?: { [key: string]: boolean; };
}

/**
 * Check if a given object implements the Mode interface.
 */
export function instanceOfMode(value: object): value is Mode {
    return true;
}

export function ModeFromJSON(json: any): Mode {
    return ModeFromJSONTyped(json, false);
}

export function ModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mode {
    if (json == null) {
        return json;
    }
    return {

        'model': json['model'] == null ? undefined : json['model'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'tools': json['tools'] == null ? undefined : json['tools'],
    };
}

export function ModeToJSON(json: any): Mode {
    return ModeToJSONTyped(json, false);
}

export function ModeToJSONTyped(value?: Mode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'model': value['model'],
        'prompt': value['prompt'],
        'tools': value['tools'],
    };
}
