/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Model } from './Model';
import {
    ModelFromJSON,
    ModelFromJSONTyped,
    ModelToJSON,
    ModelToJSONTyped,
} from './Model';

/**
 *
 * @export
 * @interface Provider
 */
export interface Provider {
    /**
     *
     * @type {string}
     * @memberof Provider
     */
    api?: string;
    /**
     *
     * @type {string}
     * @memberof Provider
     */
    name?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof Provider
     */
    env?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof Provider
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Provider
     */
    npm?: string;
    /**
     *
     * @type {{ [key: string]: Model; }}
     * @memberof Provider
     */
    models?: { [key: string]: Model; };
}

/**
 * Check if a given object implements the Provider interface.
 */
export function instanceOfProvider(value: object): value is Provider {
    return true;
}

export function ProviderFromJSON(json: any): Provider {
    return ProviderFromJSONTyped(json, false);
}

export function ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provider {
    if (json == null) {
        return json;
    }
    return {

        'api': json['api'] == null ? undefined : json['api'],
        'name': json['name'] == null ? undefined : json['name'],
        'env': json['env'] == null ? undefined : json['env'],
        'id': json['id'] == null ? undefined : json['id'],
        'npm': json['npm'] == null ? undefined : json['npm'],
        'models': json['models'] == null ? undefined : (mapValues(json['models'], ModelFromJSON)),
    };
}

export function ProviderToJSON(json: any): Provider {
    return ProviderToJSONTyped(json, false);
}

export function ProviderToJSONTyped(value?: Provider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'api': value['api'],
        'name': value['name'],
        'env': value['env'],
        'id': value['id'],
        'npm': value['npm'],
        'models': value['models'] == null ? undefined : (mapValues(value['models'], ModelToJSON)),
    };
}
