/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SendMessageRequestFilesInner
 */
export interface SendMessageRequestFilesInner {
    /**
     *
     * @type {string}
     * @memberof SendMessageRequestFilesInner
     */
    path?: string;
    /**
     *
     * @type {string}
     * @memberof SendMessageRequestFilesInner
     */
    content?: string;
}

/**
 * Check if a given object implements the SendMessageRequestFilesInner interface.
 */
export function instanceOfSendMessageRequestFilesInner(value: object): value is SendMessageRequestFilesInner {
    return true;
}

export function SendMessageRequestFilesInnerFromJSON(json: any): SendMessageRequestFilesInner {
    return SendMessageRequestFilesInnerFromJSONTyped(json, false);
}

export function SendMessageRequestFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequestFilesInner {
    if (json == null) {
        return json;
    }
    return {

        'path': json['path'] == null ? undefined : json['path'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SendMessageRequestFilesInnerToJSON(json: any): SendMessageRequestFilesInner {
    return SendMessageRequestFilesInnerToJSONTyped(json, false);
}

export function SendMessageRequestFilesInnerToJSONTyped(value?: SendMessageRequestFilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'path': value['path'],
        'content': value['content'],
    };
}
