/* tslint:disable */
/* eslint-disable */
/**
 * kuuzuki
 * kuuzuki API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendMessageRequestFilesInner } from './SendMessageRequestFilesInner';
import {
    SendMessageRequestFilesInnerFromJSON,
    SendMessageRequestFilesInnerFromJSONTyped,
    SendMessageRequestFilesInnerToJSON,
    SendMessageRequestFilesInnerToJSONTyped,
} from './SendMessageRequestFilesInner';

/**
 *
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
    /**
     *
     * @type {string}
     * @memberof SendMessageRequest
     */
    text?: string;
    /**
     *
     * @type {Array<SendMessageRequestFilesInner>}
     * @memberof SendMessageRequest
     */
    files?: Array<SendMessageRequestFilesInner>;
}

/**
 * Check if a given object implements the SendMessageRequest interface.
 */
export function instanceOfSendMessageRequest(value: object): value is SendMessageRequest {
    return true;
}

export function SendMessageRequestFromJSON(json: any): SendMessageRequest {
    return SendMessageRequestFromJSONTyped(json, false);
}

export function SendMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequest {
    if (json == null) {
        return json;
    }
    return {

        'text': json['text'] == null ? undefined : json['text'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(SendMessageRequestFilesInnerFromJSON)),
    };
}

export function SendMessageRequestToJSON(json: any): SendMessageRequest {
    return SendMessageRequestToJSONTyped(json, false);
}

export function SendMessageRequestToJSONTyped(value?: SendMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'text': value['text'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(SendMessageRequestFilesInnerToJSON)),
    };
}
