name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "kuuzuki-v*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.0"
          cache: true
          cache-dependency-path: packages/tui/go.sum

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Publish to npm
        run: |
          bun install
          bun run script/publish.ts
        working-directory: ./packages/kuuzuki
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          gh release create v${VERSION} --title "v${VERSION}" --notes "Release v${VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: publish
    if: always()
    uses: ./.github/workflows/notify-discord.yml
    secrets: inherit